services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - ${POSTGRES_PGDATA}:/var/lib/postgresql/data
    env_file: .env

  backend:
    depends_on:
      - db
    build: ./backend
    env_file: .env
    expose:
      - ${BACKEND_PORT}

  frontend:
    build: ./frontend
    expose:
      - ${FRONTEND_PORT}
    ports:
      - "80:8001"
