services:
  db:
    image: postgres
    container_name: db
    # no build dir
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ${POSTGRES_PGDATA}:/var/lib/postgresql/data
    env_file: .env

  backend:
    container_name: backend
    build: ./backend
    restart: always
    depends_on:
      - db
    env_file: .env
    expose:
      - ${BACKEND_PORT}

  frontend:
    container_name: frontend
    build: ./frontend
    expose:
      - ${FRONTEND_PORT}
    ports:
      - "80:8001"
      - "443:443"
    restart: always
    volumes:
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d:ro
      - ${LETSENCRYPT_CONFIG_DIR}:/etc/letsencrypt:ro
